### ISSUE TITLE
 Frame range doesn't match time for .mov preview files

### ISSUE THREAD

**Issue by WojtekFus** [cgwire/kitsu#1164]
**Context**

Kitsu version: Kitsu 0.17.19
Production type: Short Film

**Describe the bug**

Once .mov is uploaded for the shot task its frame range extends way beyond its runtime. A shot below is 355 frames long, but the preview shows it's 2840 frames long. Once I move the cursor beyond the frame range it simply shows the frame 355. This doesn't happen for .mp4 files. Am I missing something? Help appreciated :) 

**Screenshots**
![image](https://github.com/cgwire/kitsu/assets/143895464/83f36fc9-9a63-4ee2-b3d6-e0b8a6bf21e6)

**Desktop (please complete the following information):**

 - OS: deployed through Docker on Synology NAS
 - Browser: Edge

**Comment by frankrousseau** [comment]
Hello @WojtekFus,

It seems to be a FFMPEG bug. We have to add an empty audio track on every movie that doesn't have a soundtrack. During this operation, FFMPEG messes up with frames. If you have any idea how to solve this, please share it because we currently don't know how to fix it.

The other option is to add the silent audio track yourself in your software.
