### ISSUE TITLE
Team Members for assigning to tasks

### ISSUE THREAD

**Issue by FrancoisMaree** [cgwire/kitsu#256]
Not sure if this was by design, so apologies if this is how it is supposed to work.

I've created a project, added some assets and shots. Then I created a team based on the list of people working at the studio that I have added. If I then assign tasks to an asset, and try to assign team members to the tasks, I get shown the list of all the people in the studio, and not just the people that are the team members of the project.

**Comment by frankrousseau** [comment]
Hello @FrancoisMaree, it's the default behavior when you have less than 10 active people in your Kitsu database.  We consider that it's easier for small studios.
If there are more than 10 people registered, it acts as expected.

**Comment by BigRoy** [comment]
Interesting to see this question asked - I wondered this too and what exactly the "project team" would be since indeed I would list all users.

I wonder if this somehow needs an option of its own, for example maybe a toggle that says: "Show all artists in Project task assignments when less than X people exist in Studio."

Admittedly I wouldn't have thought it would change magically around 10 people, or is it mentioned somewhere?

**Comment by FrancoisMaree** [comment]
Ah awesome @frankrousseau. That is good to know. Thanks.
