### ISSUE TITLE
Linking Kitsu and Blender

### ISSUE THREAD

**Issue by johnnycoolideer** [cgwire/kitsu#806]
Kitsu installed lovely on the server which is fab.  Now we’re trying to link the server to Blender 3.0 in Windows.  I’ve copied the add on folder into the directory and initiated the install but it’s not showing up as an add on.  Any ideas?

**Comment by EvanBldy** [comment]
Hello @johnnycoolideer
Which addon do you use ? 
This one https://github.com/cgwire/kitsu-publisher-next which will be the new Kitsu Publisher ? or this one https://github.com/cgwire/kitsu-publisher-deprecated which is not maintened anymore ? 
Can you post this issue in the project that you use? Because it doesn't seems to be related to the frontend of Kitsu.
Thanks in advance :)
